title: Flex Launcher
description: A customizable HTPC application launcher and front-end interface
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: complexlogic
repository: complexlogic/flex-launcher
launcher_version: 2.2

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag


